name: Build and Test
on: [push, pull_request]
jobs:

  build-job:
    name: Build for PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php: ['8.0'] ##, '8.1', '8.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=-1, display_errors=On
          coverage: none

      - name: PHPize extension
        run: phpize

      - name: Configure extension
        run: ./configure --enable-canbus

      - name: Install linux-can/can-utils
        run: sudo apt install -y can-utils

      - name: Install DKMS
        run: sudo apt install -y dkms

      - name: Install kernel headers
        run: sudo apt install linux-headers-$(uname -r)

      - name: make
        run: make

      - name: test
        run: env NO_INTERACTION=1 make test